# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Generate_Rho_c <- function(Gamma, p, a_rho, b_rho) {
    .Call(`_ReciprocalGraphicalModels_Generate_Rho_c`, Gamma, p, a_rho, b_rho)
}

Generate_Psi_c <- function(Phi, d, a_psi, b_psi) {
    .Call(`_ReciprocalGraphicalModels_Generate_Psi_c`, Phi, d, a_psi, b_psi)
}

Generate_Eta_c <- function(b, phi, a_eta, b_eta, nu_2) {
    .Call(`_ReciprocalGraphicalModels_Generate_Eta_c`, b, phi, a_eta, b_eta, nu_2)
}

Generate_Tau_c <- function(a, gamma, a_tau, b_tau, nu_1) {
    .Call(`_ReciprocalGraphicalModels_Generate_Tau_c`, a, gamma, a_tau, b_tau, nu_1)
}

Generate_Sigma_c <- function(n, z_sum, a_sigma, b_sigma) {
    .Call(`_ReciprocalGraphicalModels_Generate_Sigma_c`, n, z_sum, a_sigma, b_sigma)
}

Target_Agamma_c <- function(X, Y, A, diag_p, a, N, Sigma_Inv, B, gamma, tau, rho, nu_1) {
    .Call(`_ReciprocalGraphicalModels_Target_Agamma_c`, X, Y, A, diag_p, a, N, Sigma_Inv, B, gamma, tau, rho, nu_1)
}

Generate_Agamma_C <- function(X, Y, A, diag_p, i, j, Sigma_Inv, N, B, gamma, tau, rho, nu_1, prop_var1) {
    .Call(`_ReciprocalGraphicalModels_Generate_Agamma_C`, X, Y, A, diag_p, i, j, Sigma_Inv, N, B, gamma, tau, rho, nu_1, prop_var1)
}

